# Notification is intentionally NOT registered with the admin — notifications are
# generated by the system (order emails, password reset, low-stock alerts) and
# surfaced in the account UI, not managed by staff. Removing the registration
# hides the "Notify › Notifications" entry from /admin/ without affecting the model.
