# Generated by Django 6.1 on 2026-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits_ar',
            field=models.TextField(blank=True, help_text='One benefit per line — matches الفوائد (AR).'),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_en',
            field=models.TextField(blank=True, help_text="One benefit per line — matches the live site's Benefits (EN) bullet list."),
        ),
    ]
