# Generated by Django 6.1 on 2026-08-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_benefits_ar_product_benefits_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ar_machine_translated',
            field=models.BooleanField(default=False, help_text='Arabic name/description was machine-translated — review before treating as final.'),
        ),
        migrations.AddField(
            model_name='category',
            name='ar_machine_translated',
            field=models.BooleanField(default=False, help_text='Arabic name/description was machine-translated — review before treating as final.'),
        ),
        migrations.AddField(
            model_name='product',
            name='ar_machine_translated',
            field=models.BooleanField(default=False, help_text='Arabic name/description was machine-translated — review before treating as final.'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='ar_machine_translated',
            field=models.BooleanField(default=False, help_text='Arabic value was machine-translated — review before treating as final.'),
        ),
    ]
