# Generated by Django 6.1 on 2026-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('hero', 'Hero (top of page)'), ('section_1', 'Section 1 (between rails)'), ('section_2', 'Section 2 (between rails)'), ('section_3', 'Section 3 (between rails)')], help_text='Which homepage position this video fills.', max_length=32)),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file, OR set an external video URL below — not both.', upload_to='homepage/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External (e.g. CDN-hosted) video URL, as an alternative to uploading a file.')),
                ('poster_image', models.ImageField(blank=True, help_text='Shown while the video loads or if autoplay is blocked.', null=True, upload_to='homepage/posters/')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('subtitle_ar', models.CharField(blank=True, max_length=300)),
                ('link_url', models.CharField(blank=True, help_text='Where clicking the video / banner navigates (relative or absolute).', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Dr Rashel Jo', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_text_en', models.TextField(blank=True)),
                ('about_text_ar', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed iframe src (the one from Share → Embed a map).', max_length=1000)),
                ('map_open_url', models.URLField(blank=True, help_text='Plain maps.google.com link for the "Open in Maps" button.', max_length=1000)),
                ('copyright_text_en', models.CharField(blank=True, help_text='Leave blank to auto-generate from site_name and the current year.', max_length=300)),
                ('copyright_text_ar', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
