# Generated by Django 6.1 on 2026-09-01
#
# PERFORMANCE — review before deploying. Adds three B-tree indexes to
# orders_order (status, created_at desc, (user, status)). On PostgreSQL a plain
# AddIndex takes an ACCESS EXCLUSIVE lock for the build; the orders table is
# small now (~10^2-10^3 rows) so this is milliseconds, but if it has grown by
# deploy time, apply the equivalent CREATE INDEX CONCURRENTLY by hand instead
# and fake this migration.
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0003_order_coupon_code_order_discount_amount_and_more'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
    ]
